
create table "public"."supplier2" (
    "id" bigint UNIQUE not null,
    "tsr_id" bigint UNIQUE not null default cast (generate_yymm_random_id(4) as bigint), 
    "tdb_id" bigint UNIQUE not null default cast (generate_yymm_random_id(4) as bigint), 
    "description" text
);

create table "public"."kihou2" (
  "id" bigint generated by default as identity not null,
  "insert_at" timestamp with time zone default now(),
  "year" serial,
  "code" bigint,
  FOREIGN KEY (code) REFERENCES supplier2 (id),
  "取引先名" text,
  "順位" text,
  "資材合計S" text,
  "外注合計G" text,
  "全体SG" text,
  "工具" text,
  "軸受" text,
  "油圧" text,
  "ＣＨ" text,
  "工作機" text,
  "ロボット" text,
  "マテリアル" text,
  "サーモテック" text,
  "本社" text,
  "関係会社" text,
  "主要部門" text
);





CREATE FUNCTION supplier_fn() RETURNS trigger AS $supplier_fn$  --引数なし、戻り値trigger型の関数として宣言 
BEGIN
  INSERT INTO supplier (id, tsr_id, tdb_id)
	  VALUES (NEW.id, NEW.tsr_id, NEW.tdb_id);  
  RETURN NEW;  --trigger型変数のNEWをRETURNする。
END;
$supplier_fn$
LANGUAGE plpgsql;

CREATE TRIGGER suppliers_trg AFTER INSERT ON companies FOR EACH ROW
EXECUTE FUNCTION supliers_fn();



INSERT INTO operand2 VALUES(1,2,3);
